CREATE TABLE TEMP_DATA
(
    ID   BIGSERIAL    PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL
);

INSERT INTO TEMP_DATA (NAME) VALUES ('AAAAA');
INSERT INTO TEMP_DATA (NAME) VALUES ('BBBBB');
INSERT INTO TEMP_DATA (NAME) VALUES ('CCCCC');
INSERT INTO TEMP_DATA (NAME) VALUES ('DDDDD');
