spring.application.name=Backend
spring.datasource.url=jdbc:h2:mem:PSK_DB;MODE=PostgreSQL;
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=123
spring.h2.console.enabled=true
spring.h2.console.path=/h2
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.sql.init.mode=always
spring.sql.init.platform=h2
spring.sql.init.schema-locations=classpath:Database/CREATE_TABLES.sql
spring.sql.init.data-locations=classpath:Database/ADD_DATA.sql
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE